FROM node:18
WORKDIR /usr/src/app
COPY . .
RUN npm cache clean --force
RUN rm -rf node_modules && rm -f package-lock.json
RUN npm install -g npm
RUN npm install --force
EXPOSE 3000
CMD ["npm", "start"]